name: armenu_app
description: A new Flutter application for Finer.menu
version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.0
  flutter_svg: ^0.19.1
  provider: ^4.3.3
  firebase_core: 0.7.0
  firebase_auth: ^0.20.0+1
  cloud_firestore: ^0.16.0
  google_sign_in: ^4.5.9
  flutter_facebook_auth: ^2.0.2
  firebase_storage: ^7.0.0
  image_picker: ^0.6.7+22
  permission_handler: ^5.1.0+2
  salomon_bottom_bar: ^2.0.1
  credit_card: 0.1.6
  customappbar: ^1.0.0


dev_dependencies:
  flutter_test:
    sdk: flutter


flutter:

  uses-material-design: true

  assets:
   - assets/images/
   - assets/icons/

  fonts:
    - family: Galano
      fonts:
        - asset: assets/fonts/Galano-Regular.ttf
        - asset: assets/fonts/Galano-Medium.ttf
        - asset: assets/fonts/Galano-SemiBold.ttf